version: '3'

# Если  Spring Boot приложение не имеет явных настроек(app.yml) для соединения с Kafka,
# то по умолчанию запросы будут отправляться на локальный порт 9092, где обычно работает Kafka.
#а потом пеиенаправляться на порт контейнера 9092:9092

services:
  zookeeper:
    image: wurstmeister/zookeeper
    # можно НЕ указывать порт!!!! 2181 для сервиса Zookeeper, поскольку внешний доступ к Zookeeper не требуется, и контейнер Kafka будет общаться с контейнером Zookeeper внутри сети Docker. 
    #!!ports:
    #!!! - 2181:2181
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
 #порт становится занятым после запуска кафки сервера а на локалке мы ничего не запускали
    environment:
      # ВЫБОРОЧНАЯ НАСТРОЙКА!
      KAFKA_ADVERTISED_HOST_NAME: localhost
      # ОБЯЗАТЕЛЬНАЯ НАСТРОЙКА как подключаться к Zookeeper для управления состоянием кластера Kafka. 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # это настройка, которая создает тестовую тему "test_topic" с одним репликой и тремя партициями при запуске контейнера Kafka.
      KAFKA_CREATE_TOPIC: "test_topic:1:3"


#создаем 2 контейнера(zookeeper+кафка) сначала запускается zookeeper потом кафка а приложение будет реальным yml не требуется все будет в компоусе
#zookeeper запускается по умолчанию на порту 2181
#потом запускается сам кафка на порту 9092(почему он не занят нашим локалом?потому что порт становится занятым у кафки когда он именно запущен а запускается через 2 команды)
#зачем нужен порт маппинг? наш спринг по умолчанию отправит запросы на порт 9092 локалки!!а там уже произойдет перенаправление на порт контейнера!!!
#потому что другого способа достучаться к контейнеру нет!
#как кафка свяжется с zookeeper? через сервисное пространство докера!по имени! вот в этом пункте
#KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 -> вместо локалхост пишем имя сервиса zookeeper!!
#порт у zookeeper не нужен потому что когда запустится кафка он сам найдет zookeeper по имени (KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181)
